name: react-nginx
services:
  frontend:
    build:
      context: /home/roberto/practice_docker_kubernetes/awesome-compose/react-nginx
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    volumes:
    - type: bind
      source: /home/roberto/practice_docker_kubernetes/awesome-compose/react-nginx/pipeline.sh
      target: /pipeline.sh
      bind:
        create_host_path: true
networks:
  default:
    name: react-nginx_default
